package com.cdc.framework.utils;

public enum DatabaseVendor {
    POSTGRESQL, MYSQL,MARIADB,SQLSERVER, ORACLE, DB2,MONGODB,CASSANDRA, VITESS, SNOWFLAKE, REDSHIFT, BIGQUERY, HIVE, TERADATA, SYBASE, INFORMIX, SQLITE, FIREBIRD, H2, DERBY, COUCHBASE, ELASTICSEARCH, DYNAMODB
}
