spring.application.name=cdc-transformation-service
server.port=8081
# H2 in-memory DB for local CDC testing
spring.datasource.url=jdbc:h2:mem:test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS public
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false

# H2 web console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.debug=true
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false

management.endpoints.web.exposure.include=health, info, metrics, prometheus
management.endpoints.health.show-details=always



# Kafka defaults




# spring
# spring.kafka.bootstrap-servers=localhost:9092
# spring.kafka.consumer.group-id=cdc-transformation-group
# spring.kafka.consumer.auto-offset-reset=earliest
# spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# # Debezium defaults for local capture
# debezium.database.hostname=localhost
# debezium.database.port=5432
# debezium.database.user=postgres
# debezium.database.password=postgres
# debezium.database.dbname=postgres
# debezium.database.server.name=cdc-server
# debezium.snapshot.mode=initial
# debezium.table.include.list=
